apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mga5ie1jo-python
  janus-idp.io/tekton: mga5ie1jo-python
  backstage.io/kubernetes-id: mga5ie1jo-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mga5ie1jo-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
